### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by thh32** [tlubitz/SBtab#52] opened 2018-08-27 13:51 UTC
I have tried installing the python version by running `python setup.py install` within the `pypi_installer` folder.

When I attempt to import the module in python the following happens;

`>>> import SBtab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SBtab.py", line 185
SyntaxError: Non-ASCII character '\xe2' in file SBtab.py on line 185, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`
Is there a solution for this?

**Comment by tlubitz** [comment] 2018-08-27 20:32
Hi Thomas,

the pypi installer folder is just our system folder for building the pypi installer. It is not intended to be installed the way you describe it. The Python version that you want to install you can get by typing

sudo pip3 install sbtab

on your commandline. You do not require the contents of the pypi folder. Let me know if this clarifies the problem.

**Comment by thh32** [comment] 2018-08-28 07:02
That seems to have installed fine (no error messages), how then do you run the `sbml2sbtab.py` script as currently the following issues occur;

```
$ python3 sbml2sbtab.py 
Traceback (most recent call last):
  File "/home/thomashitch/Downloads/sbtab-0.9.19/sbtab/SBtab.py", line 16, in <module>
    from . import misc
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sbml2sbtab.py", line 11, in <module>
    try: import SBtab
  File "/home/thomashitch/Downloads/sbtab-0.9.19/sbtab/SBtab.py", line 18, in <module>
    import misc
  File "/home/thomashitch/Downloads/sbtab-0.9.19/sbtab/misc.py", line 6, in <module>
    import scipy
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sbml2sbtab.py", line 12, in <module>
    except: from . import SBtab
ImportError: cannot import name 'SBtab'



$ python sbml2sbtab.py 
Traceback (most recent call last):
  File "sbml2sbtab.py", line 12, in <module>
    except: from . import SBtab
ValueError: Attempted relative import in non-package

```

**Comment by thh32** [comment] 2018-08-28 07:03
Thanks this seems to work now! I look forward to using your program

**Comment by tlubitz** [comment] 2018-08-28 08:51
Hi Tom,

sorry for the confusion. You are currently using two different versions of the software:

When you install the SBtab package via the pip installer (sudo pip3 install sbtab) then you can import sbtab in your Python scripts (via import sbtab). This does not necessarily enable you to use SBtab on command line.

When you want to use SBtab on command line (which is for experienced users who install the required packages on their own), you will have to gather the required scripts from the SBtab/python directory and follow the instructions on github.

As a matter of fact, there are very current alterations on the user interface, which is most probably also causing your error. The problem is mainly that the documentation on how to use either the pip version or the command line version is outdated. Give me some time to work this over, then everything will become much clearer again.

Again, sorry for the confusion,
Best,
Timo

**Comment by tlubitz** [comment] 2018-10-18 12:13
Hi Thomas,

if this issue is resolved by now I'll close this report. Let me know if it persists or if there is any other trouble.

Best,
Timo

**Closed** 2018-10-22 10:07 UTC
